[Variables]

Location=SPXX0050
Unit=m
ScrollMouseIncrement=0.05
Format=H
Hidden=0
Hidden2=1
Player=Winamp
Color1=224,180,209
Color2=142,193,250
Color3=0,0,0
UserName=Connect-R


;NOTES:

;This below is the settings for the dock with icons.
;If you are not familiar with Rainmeter from earlier,please don't edit anything!
;It's too complicated and sensitive,if you don't know what you doing!
;But i will try to explain to you as much as i can.This "#@#\" is shortened for "@Resources" folder.It's a folder where the icons and other parts of the skin are located.
;If you want to change icon-s,new icon-s,you must put in "@Resources" folder.Also,icons must be in PNG file format.
;When you change "icon and name path",for example if you want to change "My Computer" icon to "CCleaner",it should look like this:

;This is example for some program:

;
;Name1=CCleaner
;LocationPath1=["C:\Program Files\CCleaner\CCleaner64.exe"]

;This is example for some internet links:

;Name2=Twitter
;LocationPath2=["https://twitter.com/?lang=en"]

;etc..

;On this site : https://docs.rainmeter.net/manual/getting-started/customizing/
;you can find all information,about customizing some skin.To change color,font,size,etc..
;You can also learn how to make your first skin. :)
;Thank you for your understanding! :)


;----------------------Folder Settings-------------------------------
;--------------------------------------------------------------------


Name1=My Computer
LocationPath1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Name2=My Documents
LocationPath2=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]

Name3=Video
LocationPath3=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

Name4=Music
LocationPath4=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

Name5=Pictures
LocationPath5=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

Name6=Downloads
LocationPath6=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]


;----------------------Link Settings-------------------------------
;------------------------------------------------------------------

Name7=Google
LocationPath7=["https://google.com"]

Name8=Facebook
LocationPath8=["https://facebook.com/"]

Name9=Gmail
LocationPath9=["https://mail.google.com/mail/"]

Name10=YouTube
LocationPath10=["https://www.youtube.com/"]

Name11=Reddit
LocationPath11=["https://www.reddit.com/"]

Name12=Deviantart
LocationPath12=["https://www.deviantart.com/"]

Name13=Instagram
LocationPath13=["https://www.instagram.com/"]

Name14=Pinterest
LocationPath14=["https://www.pinterest.com/"]

Name15=Tweeter
LocationPath15=["https://twitter.com/"]


;----------------------Icon Dock Settings--------------------------
;------------------------------------------------------------------


Icon1NameAndPath=#@#\My Computer.png
TextName1=My Computer
LocationPath1=[Shell:::{20D04FE0-3AEA-1069-A2D8-08002B30309D}]

Icon2NameAndPath=#@#\My Documents.png
TextName2=My Documents
LocationPath2=[Shell:::{A8CDFF1C-4878-43be-B5FD-F8091C1C60D0}]

Icon3NameAndPath=#@#\Video.png
TextName3=Video
LocationPath3=[Shell:::{A0953C92-50DC-43bf-BE83-3742FED03C9C}]

Icon4NameAndPath=#@#\Music.png
TextName4=Music
LocationPath4=[Shell:::{1CF1260C-4DD0-4ebb-811F-33C572699FDE}]

Icon5NameAndPath=#@#\Picture.png
TextName5=Pictures
LocationPath5=[Shell:::{3ADD1653-EB32-4cb0-BBD7-DFA0ABB5ACCA}]

Icon6NameAndPath=#@#\Downloads.png
TextName6=Downloads
LocationPath6=[Shell:::{374DE290-123F-4565-9164-39C4925E467B}]

Icon7NameAndPath=#@#\Internet.png
TextName7=Internet
LocationPath7=["https://google.com"]

Icon8NameAndPath=#@#\Email.png
TextName8=Email
LocationPath8=["https://mail.google.com/mail/"]

Icon9NameAndPath=#@#\Facebook.png
TextName9=Facebook
LocationPath9=["https://facebook.com/"]

Icon10NameAndPath=#@#\Tweeter.png
TextName10=Tweeter
LocationPath10=["https://twitter.com/"]

Icon11NameAndPath=#@#\Deviantart.png
TextName11=Deviantart
LocationPath11=["https://www.deviantart.com/"]

Icon12NameAndPath=#@#\Reddit.png
TextName12=Reddit
LocationPath12=["https://www.reddit.com/"]

